language: cpp
sudo: false

git:
  depth: 1

services:
  - postgresql

addons:
  postgresql: "9.6"
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - postgresql-9.6-postgis-2.3
    - python-psycopg2
    - libexpat1-dev
    - libpq-dev
    - libbz2-dev
    - libproj-dev
    - lua5.2
    - liblua5.2-dev
    - libluajit-5.1-dev
    - libboost1.55-dev
    - libboost-system1.55-dev
    - libboost-filesystem1.55-dev

matrix:

  include:
    - os: linux
      compiler: clang
      sudo: false
      env: T="clang_dbtest" RUNTEST="#All-db" CXXFLAGS="-pedantic -Werror" LUAJIT_OPTION="OFF"

    - os: linux
      compiler: gcc
      sudo: required
      env: T="gcc4asan_NoDB" RUNTEST="-L NoDB" CXXFLAGS="-pedantic -Werror -fsanitize=address" LUAJIT_OPTION="OFF"

    - os: linux
      compiler: gcc
      sudo: required
      env: T="gcc4asan_dbtest" RUNTEST="#All-db" CXXFLAGS="-pedantic -Werror -fsanitize=address" LUAJIT_OPTION="OFF"

    - os: linux
      compiler: clang
      sudo: false
      env: T="clang_notest_luajit"  CXXFLAGS="-pedantic -Werror" LUAJIT_OPTION="ON"

    - os: linux
      compiler: gcc
      sudo: required
      env: T="gcc4asan_NoDB_luajit" RUNTEST="-L NoDB" CXXFLAGS="-pedantic -Werror -fsanitize=address" LUAJIT_OPTION="ON"

    - os: osx
      compiler: clang
      sudo: false
      env: T="osx_clang_NoDB" RUNTEST="-L NoDB" CXXFLAGS="-pedantic -Werror " LUAJIT_OPTION="OFF"
      before_install:
        - brew install lua;
      before_script:
        - $CXX --version
        - xml2-config --version
        - proj | head -n1
        - lua -v

    - os: linux
      compiler: gcc-7
      sudo: required
      env: T="gcc7_dbtest_luajit" RUNTEST="#All-dbtest" CXXFLAGS=" -pedantic -Werror" LUAJIT_OPTION="ON"
      addons:
        postgresql: "9.6"
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-7
          - postgresql-9.6-postgis-2.3
          - python-psycopg2
          - libexpat1-dev
          - libpq-dev
          - libbz2-dev
          - libproj-dev
          - lua5.2
          - liblua5.2-dev
          - libluajit-5.1-dev
          - libboost1.55-dev
          - libboost-system1.55-dev
          - libboost-filesystem1.55-dev
      install:
      - if [[ $CC == 'gcc' ]]; then
          export CC=gcc-7;
        fi
      - if [[ $CXX == 'g++' ]]; then
          export CXX=g++-7;
        fi


    - os: linux
      compiler: gcc-8
      sudo: required
      env: T="gcc8_pg10_dbtest_luajit" RUNTEST="#All-dbtest" CXXFLAGS="-pedantic -Werror" LUAJIT_OPTION="ON"
      addons:
        postgresql: "10"
        apt:
          sources:
          - boost-latest
          - ubuntu-toolchain-r-test
          packages:
          - g++-8
          - postgresql-10-postgis-2.4
          - python-psycopg2
          - libexpat1-dev
          - libpq-dev
          - libbz2-dev
          - libproj-dev
          - lua5.2
          - liblua5.2-dev
          - libluajit-5.1-dev
          - libboost1.55-dev
          - libboost-system1.55-dev
          - libboost-filesystem1.55-dev
      install:
      - if [[ $CC == 'gcc' ]]; then
          export CC=gcc-8;
        fi
      - if [[ $CXX == 'g++' ]]; then
          export CXX=g++-8;
        fi

  allow_failures:
    - os: linux
      env: T="gcc7asan_dbtest_luajit" RUNTEST="#All-dbtest" CXXFLAGS=" -pedantic -Werror -fsanitize=address " LUAJIT_OPTION="ON"

    - os: linux
      env: T="gcc8asan_dbtest_luajit" RUNTEST="#All-dbtest" CXXFLAGS=" -pedantic -Werror -fsanitize=address " LUAJIT_OPTION="ON"

before_install:
  - sudo mkdir -p /extra/pg/tablespacetest
  - sudo chown postgres:postgres /extra/pg/tablespacetest
  # for checking available versions
  - dpkg -l | grep -E 'lua|proj|xml|bz2|postgis|zlib|boost|expat'
# update versions
install:
  - if [[ $CC == 'gcc' ]]; then
      export CC=gcc-4.8;
    fi
  - if [[ $CXX == 'g++' ]]; then
      export CXX=g++-4.8;
    fi
before_script:
  - psql -U postgres -c "CREATE TABLESPACE tablespacetest LOCATION '/extra/pg/tablespacetest'"
  - psql -U postgres -c "CREATE EXTENSION postgis"
  - psql -U postgres -c "CREATE EXTENSION hstore"
  - psql -U postgres -c "SELECT version()"
  - psql -U postgres -c "SELECT PostGIS_Full_Version()"
  - $CXX --version
  - xml2-config --version
  - proj | head -n1
  - lua -v
script:
  - mkdir build && cd build
  - cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DWITH_LUAJIT=$LUAJIT_OPTION
  - make -j2
  - echo "Running tests that does not require PostgreSQL server"
  - if [[ $RUNTEST ]]; then ctest -VV $RUNTEST; fi
after_failure:
  - # rerun make, but verbosely
    make VERBOSE=1
