version: "2.1"

services:

# docker-compose run --rm osm2pgsql-dev
  osm2pgsql-dev:
    image: "osm2pgsql-dev:gcc${GCCVER:-7}"    # docker gcc version : valid:   4,5,6,7,8
    #image: "osm2pgsql-dev:latest"    # docker gcc version : valid:   4,5,6,7,8

    cap_add:
    - SYS_PTRACE    # for the -fsanitize=address testing !

    links:
    - postgis

    volumes:
    - .:/openstreetmap/osm2pgsql 

    environment:             
    - RUNTEST="${RUNTEST}"                 # for the ctest - example:"-L NoDB"
    - CXXFLAGS="${CXXFLAGS:--Werror}"      # CXXFLAGS="-pedantic -Werror -fsanitize=address"
    - LUA_OPTION="${LUA_OPTION:-ON}"       # cmake LUA  
    - LUAJIT_OPTION="${LUAJIT_OPTION:-ON}" # cmake LUAJIT

  # Database parameters - for test! 
    - PGHOST=postgis
    - PGUSER=osm
    - PGDATABASE=osm
    - PGPASSWORD=osm
    - DB_HOST=postgis
    - DB_USER=osm
    - DB_NAME=osm
    - DB_PASS=osm

  postgis:
    image: "mdillon/postgis:10-alpine"
    volumes:
    - ./docker/tablespace.sh:/docker-entrypoint-initdb.d/tablespace.sh
    - ./temp-pgdata/10-alpine:/var/lib/postgresql/data
    ports:
    - 127.0.0.1:25433:5432    
    environment:
    - POSTGRES_DB=osm
    - POSTGRES_USER=osm
    - POSTGRES_PASSWORD=osm
    